---
- name: restart strongswan
  service: name={{ strongswan_service }} state=restarted

- name: daemon-reload
  systemd: daemon_reload=true

- name: restart apparmor
  service: name=apparmor state=restarted

- name: rereadcrls
  shell: ipsec rereadcrls; ipsec purgecrls
