---
- name: WireGuard installed
  apt:
    name: wireguard
    state: present
    update_cache: true

- name: Set OS specific facts
  set_fact:
    service_name: wg-quick@{{ wireguard_interface }}
  tags: always
