---
- name: Build python virtual environment
  import_tasks: venv.yml

- name: Include prompts
  import_tasks: prompts.yml

- name: Deploy the stack
  import_tasks: cloudformation.yml

- set_fact:
    cloud_instance_ip: "{{ stack.stack_outputs.IpAddress }}"
    ansible_ssh_user: algo
    ansible_ssh_port: "{{ ssh_port }}"
    cloudinit: true
